name: salve_financas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  go_router: ^13.2.5
  
  google_fonts: ^6.3.3
  fl_chart: ^1.1.1
  font_awesome_flutter: ^10.6.0
  
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

  # MODULARIZAÇÃO DA IA (Resolve o erro do smart_reply)
  mobile_scanner: ^5.2.3
  google_mlkit_barcode_scanning: ^0.12.0 # Para capturar o link da SEFAZ
  google_mlkit_text_recognition: ^0.12.0 # Para o OCR de notas sem QR Code
  http: ^1.6.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/salve_financas_logo.png
    - assets/data/financial_rules.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/salve_financas_logo.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/images/salve_financas_logo.png"