name: salve_financas
description: Concierge Financeiro Local.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- UI & VISUAL ---
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  flutter_markdown: ^0.7.1

  # --- DADOS ---
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2
  
  # --- NETWORK (NecessÃ¡rio para baixar o modelo) ---
  dio: ^5.4.0
  
  # --- AI LOCAL (Otimizado para Android) ---
  llama_flutter_android: ^0.1.1 
  
  # --- OUTROS ---
  go_router: ^13.2.0
  mobile_scanner: ^5.1.0
  permission_handler: ^11.3.0
  file_picker: ^8.0.0
  read_pdf_text: ^0.3.1
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.0.7
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/context_rules.json